
#include <string.h>

/*
 * This file should be included in files that want 
 * to use command-line options for sysmon.  We 
 * include the source code here because the definition
 * of gengetopt_args_info (generated by gengetopt) 
 * will change for each set of options generated by
 * the gengetopt program. 
 */

#ifndef _SYSMON_OPTS_H_
#define _SYSMON_OPTS_H_


/**
 * @brief Output the sysmon options to a specified file
 *
 * @param fp @input The file pointer.
 * @param opts @input The options to print.
 */
void print_sysmon_opts(
		FILE *fp, 
		const struct gengetopt_args_info *args_info, 
		const char *prefix)
{
	fprintf(fp, "%s ------------ Sysmon Options -----------\n", prefix);
	fprintf(fp, "%s \tmax-mem-allowed = %d\n", prefix, args_info->max_mem_allowed_arg);
}


/** 
  * @brief Load default command-line options for the logger. 
  */
int load_default_sysmon_opts(struct gengetopt_args_info *args_info)
{
	args_info->max_mem_allowed_arg = 0; 
	return 0;
}


#endif /* !_SYSMON_OPTS_H_ */
