/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "../../../../../testing/rpc-tests/lwfs-xfer/xfer.h"

bool_t
xdr_data_t (XDR *xdrs, data_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->int_val))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->float_val))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->double_val))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_data_array_t (XDR *xdrs, data_array_t *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->data_array_t_val, (u_int *) &objp->data_array_t_len, ~0,
		sizeof (data_t), (xdrproc_t) xdr_data_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_xfer_1_args (XDR *xdrs, xfer_1_args *objp)
{
	register int32_t *buf;

	 if (!xdr_data_array_t (xdrs, &objp->array))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_xfer_2_args (XDR *xdrs, xfer_2_args *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->len))
		 return FALSE;
	return TRUE;
}
