/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _XFER_H_RPCGEN
#define _XFER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data_t {
	int int_val;
	float float_val;
	double double_val;
};
typedef struct data_t data_t;

typedef struct {
	u_int data_array_t_len;
	data_t *data_array_t_val;
} data_array_t;

struct xfer_1_args {
	data_array_t array;
};
typedef struct xfer_1_args xfer_1_args;

struct xfer_2_args {
	int len;
};
typedef struct xfer_2_args xfer_2_args;

#define XFER_PROG 0x23451111
#define XFER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define xfer 1
extern  data_t * xfer_1(data_array_t *, CLIENT *);
extern  data_t * xfer_1_svc(data_array_t *, struct svc_req *);
extern int xfer_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define xfer 1
extern  data_t * xfer_1();
extern  data_t * xfer_1_svc();
extern int xfer_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data_t (XDR *, data_t*);
extern  bool_t xdr_data_array_t (XDR *, data_array_t*);
extern  bool_t xdr_xfer_1_args (XDR *, xfer_1_args*);
extern  bool_t xdr_xfer_2_args (XDR *, xfer_2_args*);

#else /* K&R C */
extern bool_t xdr_data_t ();
extern bool_t xdr_data_array_t ();
extern bool_t xdr_xfer_1_args ();
extern bool_t xdr_xfer_2_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_XFER_H_RPCGEN */
