/*
  File autogenerated by gengetopt version 2.17
  generated with the following command:
  /home/raoldfi/software/i386/bin/gengetopt -S --set-package=lwfs-tests --set-version=0.1 --output-dir=../../../../testing/ss-tests 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: lwfs-tests [OPTIONS]...";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                   Print help and exit",
  "  -V, --version                Print version and exit",
  "      --cid=INT                The container ID to use  (default=`1')",
  "      --oid=INT                The object ID to use  (default=`1')",
  "      --num-objs=INT           The number of object to create/remove/...  \n                                 (default=`1')",
  "      --data=STRING            Character string stored in an object  \n                                 (default=`hello world')",
  "      --trunc-size=INT         Size (bytes) of a file after the trunc test  \n                                 (default=`32')",
  "      --attr-name=STRING       Name of an attribute  (default=`testattr')",
  "      --attr-val=STRING        Value to store in an attribute  \n                                 (default=`testvalue')",
  "      --test=STRING            Name of the test  (possible values=\"exists\", \n                                 \"create\", \"read\", \"write\", \"setattr\", \n                                 \"getattr\", \"listattr\", \"rmattr\", \n                                 \"stat\", \"remove\" default=`exists')",
  "      --verbose=INT            Debug level of logger [0-5]  (default=`5')",
  "      --logfile=STRING         Path to logfile",
  "      --authr-pid=LONG         PID of the authr server  (default=`124')",
  "      --authr-nid=LONG         NID of the authr server  (default=`0')",
  "      --authr-cache-caps       Cache caps on the client  (default=off)",
  "      --ss-server-file=STRING  Path to a file with a list of storage servers",
  "      --ss-num-servers=INT     Number of servers to use from the server file  \n                                 (default=`1')",
  "      --ss-pid=INT             The PID of a single remote storage storage \n                                 server (ignored if using --ss=server-file)  \n                                 (default=`122')",
  "      --ss-nid=LONG            The NID of a single remote storage server \n                                 (ignored if using --ss-server-file)  \n                                 (default=`0')",
    0
};

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);
struct line_list
{
  char * string_arg;
  struct line_list * next;
};

static struct line_list *cmd_line_list = 0;
static struct line_list *cmd_line_list_tmp = 0;

static void
free_cmd_list(void)
{
  /* free the list of a previous call */
  if (cmd_line_list)
    {
      while (cmd_line_list) {
        cmd_line_list_tmp = cmd_line_list;
        cmd_line_list = cmd_line_list->next;
        free (cmd_line_list_tmp->string_arg);
        free (cmd_line_list_tmp);
      }
    }
}


char *cmdline_parser_test_values[] = {"exists", "create", "read", "write", "setattr", "getattr", "listattr", "rmattr", "stat", "remove", 0} ;	/* Possible values for test.  */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->cid_given = 0 ;
  args_info->oid_given = 0 ;
  args_info->num_objs_given = 0 ;
  args_info->data_given = 0 ;
  args_info->trunc_size_given = 0 ;
  args_info->attr_name_given = 0 ;
  args_info->attr_val_given = 0 ;
  args_info->test_given = 0 ;
  args_info->verbose_given = 0 ;
  args_info->logfile_given = 0 ;
  args_info->authr_pid_given = 0 ;
  args_info->authr_nid_given = 0 ;
  args_info->authr_cache_caps_given = 0 ;
  args_info->ss_server_file_given = 0 ;
  args_info->ss_num_servers_given = 0 ;
  args_info->ss_pid_given = 0 ;
  args_info->ss_nid_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->cid_arg = 1;
  args_info->cid_orig = NULL;
  args_info->oid_arg = 1;
  args_info->oid_orig = NULL;
  args_info->num_objs_arg = 1;
  args_info->num_objs_orig = NULL;
  args_info->data_arg = gengetopt_strdup ("hello world");
  args_info->data_orig = NULL;
  args_info->trunc_size_arg = 32;
  args_info->trunc_size_orig = NULL;
  args_info->attr_name_arg = gengetopt_strdup ("testattr");
  args_info->attr_name_orig = NULL;
  args_info->attr_val_arg = gengetopt_strdup ("testvalue");
  args_info->attr_val_orig = NULL;
  args_info->test_arg = gengetopt_strdup ("exists");
  args_info->test_orig = NULL;
  args_info->verbose_arg = 5;
  args_info->verbose_orig = NULL;
  args_info->logfile_arg = NULL;
  args_info->logfile_orig = NULL;
  args_info->authr_pid_arg = 124;
  args_info->authr_pid_orig = NULL;
  args_info->authr_nid_arg = 0;
  args_info->authr_nid_orig = NULL;
  args_info->authr_cache_caps_flag = 0;
  args_info->ss_server_file_arg = NULL;
  args_info->ss_server_file_orig = NULL;
  args_info->ss_num_servers_arg = 1;
  args_info->ss_num_servers_orig = NULL;
  args_info->ss_pid_arg = 122;
  args_info->ss_pid_orig = NULL;
  args_info->ss_nid_arg = 0;
  args_info->ss_nid_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{
  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->cid_help = gengetopt_args_info_help[2] ;
  args_info->oid_help = gengetopt_args_info_help[3] ;
  args_info->num_objs_help = gengetopt_args_info_help[4] ;
  args_info->data_help = gengetopt_args_info_help[5] ;
  args_info->trunc_size_help = gengetopt_args_info_help[6] ;
  args_info->attr_name_help = gengetopt_args_info_help[7] ;
  args_info->attr_val_help = gengetopt_args_info_help[8] ;
  args_info->test_help = gengetopt_args_info_help[9] ;
  args_info->verbose_help = gengetopt_args_info_help[10] ;
  args_info->logfile_help = gengetopt_args_info_help[11] ;
  args_info->authr_pid_help = gengetopt_args_info_help[12] ;
  args_info->authr_nid_help = gengetopt_args_info_help[13] ;
  args_info->authr_cache_caps_help = gengetopt_args_info_help[14] ;
  args_info->ss_server_file_help = gengetopt_args_info_help[15] ;
  args_info->ss_num_servers_help = gengetopt_args_info_help[16] ;
  args_info->ss_pid_help = gengetopt_args_info_help[17] ;
  args_info->ss_nid_help = gengetopt_args_info_help[18] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  printf("\n%s\n\n", gengetopt_args_info_usage);
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  
  if (args_info->cid_orig)
    {
      free (args_info->cid_orig); /* free previous argument */
      args_info->cid_orig = 0;
    }
  if (args_info->oid_orig)
    {
      free (args_info->oid_orig); /* free previous argument */
      args_info->oid_orig = 0;
    }
  if (args_info->num_objs_orig)
    {
      free (args_info->num_objs_orig); /* free previous argument */
      args_info->num_objs_orig = 0;
    }
  if (args_info->data_arg)
    {
      free (args_info->data_arg); /* free previous argument */
      args_info->data_arg = 0;
    }
  if (args_info->data_orig)
    {
      free (args_info->data_orig); /* free previous argument */
      args_info->data_orig = 0;
    }
  if (args_info->trunc_size_orig)
    {
      free (args_info->trunc_size_orig); /* free previous argument */
      args_info->trunc_size_orig = 0;
    }
  if (args_info->attr_name_arg)
    {
      free (args_info->attr_name_arg); /* free previous argument */
      args_info->attr_name_arg = 0;
    }
  if (args_info->attr_name_orig)
    {
      free (args_info->attr_name_orig); /* free previous argument */
      args_info->attr_name_orig = 0;
    }
  if (args_info->attr_val_arg)
    {
      free (args_info->attr_val_arg); /* free previous argument */
      args_info->attr_val_arg = 0;
    }
  if (args_info->attr_val_orig)
    {
      free (args_info->attr_val_orig); /* free previous argument */
      args_info->attr_val_orig = 0;
    }
  if (args_info->test_arg)
    {
      free (args_info->test_arg); /* free previous argument */
      args_info->test_arg = 0;
    }
  if (args_info->test_orig)
    {
      free (args_info->test_orig); /* free previous argument */
      args_info->test_orig = 0;
    }
  if (args_info->verbose_orig)
    {
      free (args_info->verbose_orig); /* free previous argument */
      args_info->verbose_orig = 0;
    }
  if (args_info->logfile_arg)
    {
      free (args_info->logfile_arg); /* free previous argument */
      args_info->logfile_arg = 0;
    }
  if (args_info->logfile_orig)
    {
      free (args_info->logfile_orig); /* free previous argument */
      args_info->logfile_orig = 0;
    }
  if (args_info->authr_pid_orig)
    {
      free (args_info->authr_pid_orig); /* free previous argument */
      args_info->authr_pid_orig = 0;
    }
  if (args_info->authr_nid_orig)
    {
      free (args_info->authr_nid_orig); /* free previous argument */
      args_info->authr_nid_orig = 0;
    }
  if (args_info->ss_server_file_arg)
    {
      free (args_info->ss_server_file_arg); /* free previous argument */
      args_info->ss_server_file_arg = 0;
    }
  if (args_info->ss_server_file_orig)
    {
      free (args_info->ss_server_file_orig); /* free previous argument */
      args_info->ss_server_file_orig = 0;
    }
  if (args_info->ss_num_servers_orig)
    {
      free (args_info->ss_num_servers_orig); /* free previous argument */
      args_info->ss_num_servers_orig = 0;
    }
  if (args_info->ss_pid_orig)
    {
      free (args_info->ss_pid_orig); /* free previous argument */
      args_info->ss_pid_orig = 0;
    }
  if (args_info->ss_nid_orig)
    {
      free (args_info->ss_nid_orig); /* free previous argument */
      args_info->ss_nid_orig = 0;
    }
  
  clear_given (args_info);
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  if (args_info->help_given) {
    fprintf(outfile, "%s\n", "help");
  }
  if (args_info->version_given) {
    fprintf(outfile, "%s\n", "version");
  }
  if (args_info->cid_given) {
    if (args_info->cid_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "cid", args_info->cid_orig);
    } else {
      fprintf(outfile, "%s\n", "cid");
    }
  }
  if (args_info->oid_given) {
    if (args_info->oid_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "oid", args_info->oid_orig);
    } else {
      fprintf(outfile, "%s\n", "oid");
    }
  }
  if (args_info->num_objs_given) {
    if (args_info->num_objs_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "num-objs", args_info->num_objs_orig);
    } else {
      fprintf(outfile, "%s\n", "num-objs");
    }
  }
  if (args_info->data_given) {
    if (args_info->data_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "data", args_info->data_orig);
    } else {
      fprintf(outfile, "%s\n", "data");
    }
  }
  if (args_info->trunc_size_given) {
    if (args_info->trunc_size_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "trunc-size", args_info->trunc_size_orig);
    } else {
      fprintf(outfile, "%s\n", "trunc-size");
    }
  }
  if (args_info->attr_name_given) {
    if (args_info->attr_name_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "attr-name", args_info->attr_name_orig);
    } else {
      fprintf(outfile, "%s\n", "attr-name");
    }
  }
  if (args_info->attr_val_given) {
    if (args_info->attr_val_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "attr-val", args_info->attr_val_orig);
    } else {
      fprintf(outfile, "%s\n", "attr-val");
    }
  }
  if (args_info->test_given) {
    if (args_info->test_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "test", args_info->test_orig);
    } else {
      fprintf(outfile, "%s\n", "test");
    }
  }
  if (args_info->verbose_given) {
    if (args_info->verbose_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "verbose", args_info->verbose_orig);
    } else {
      fprintf(outfile, "%s\n", "verbose");
    }
  }
  if (args_info->logfile_given) {
    if (args_info->logfile_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "logfile", args_info->logfile_orig);
    } else {
      fprintf(outfile, "%s\n", "logfile");
    }
  }
  if (args_info->authr_pid_given) {
    if (args_info->authr_pid_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "authr-pid", args_info->authr_pid_orig);
    } else {
      fprintf(outfile, "%s\n", "authr-pid");
    }
  }
  if (args_info->authr_nid_given) {
    if (args_info->authr_nid_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "authr-nid", args_info->authr_nid_orig);
    } else {
      fprintf(outfile, "%s\n", "authr-nid");
    }
  }
  if (args_info->authr_cache_caps_given) {
    fprintf(outfile, "%s\n", "authr-cache-caps");
  }
  if (args_info->ss_server_file_given) {
    if (args_info->ss_server_file_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "ss-server-file", args_info->ss_server_file_orig);
    } else {
      fprintf(outfile, "%s\n", "ss-server-file");
    }
  }
  if (args_info->ss_num_servers_given) {
    if (args_info->ss_num_servers_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "ss-num-servers", args_info->ss_num_servers_orig);
    } else {
      fprintf(outfile, "%s\n", "ss-num-servers");
    }
  }
  if (args_info->ss_pid_given) {
    if (args_info->ss_pid_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "ss-pid", args_info->ss_pid_orig);
    } else {
      fprintf(outfile, "%s\n", "ss-pid");
    }
  }
  if (args_info->ss_nid_given) {
    if (args_info->ss_nid_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "ss-nid", args_info->ss_nid_orig);
    } else {
      fprintf(outfile, "%s\n", "ss-nid");
    }
  }
  
  fclose (outfile);

  i = EXIT_SUCCESS;
  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/*
 * Returns:
 * - the index of the matched value
 * - -1 if no argument has been specified
 * - -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values are matched */
}


/* gengetopt_strdup() */
/* strdup.c replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;

  result = cmdline_parser_internal (argc, argv, args_info, override, initialize, check_required, NULL);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, NULL) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error = 0;

  /* checks for required options */
  
  /* checks for dependences among options */
  if (args_info->ss_num_servers_given && ! args_info->ss_server_file_given)
    {
      fprintf (stderr, "%s: '--ss-num-servers' option depends on option 'ss-server-file'%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }

  return error;
}

int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int found = 0;
      int option_index = 0;
      char *stop_char;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "cid",	1, NULL, 0 },
        { "oid",	1, NULL, 0 },
        { "num-objs",	1, NULL, 0 },
        { "data",	1, NULL, 0 },
        { "trunc-size",	1, NULL, 0 },
        { "attr-name",	1, NULL, 0 },
        { "attr-val",	1, NULL, 0 },
        { "test",	1, NULL, 0 },
        { "verbose",	1, NULL, 0 },
        { "logfile",	1, NULL, 0 },
        { "authr-pid",	1, NULL, 0 },
        { "authr-nid",	1, NULL, 0 },
        { "authr-cache-caps",	0, NULL, 0 },
        { "ss-server-file",	1, NULL, 0 },
        { "ss-num-servers",	1, NULL, 0 },
        { "ss-pid",	1, NULL, 0 },
        { "ss-nid",	1, NULL, 0 },
        { NULL,	0, NULL, 0 }
      };

      stop_char = 0;
      c = getopt_long (argc, argv, "hV", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);


        case 0:	/* Long option with no short option */
          /* The container ID to use.  */
          if (strcmp (long_options[option_index].name, "cid") == 0)
          {
            if (local_args_info.cid_given)
              {
                fprintf (stderr, "%s: `--cid' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->cid_given && ! override)
              continue;
            local_args_info.cid_given = 1;
            args_info->cid_given = 1;
            args_info->cid_arg = strtol (optarg, &stop_char, 0);
            if (!(stop_char && *stop_char == '\0')) {
              fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
              goto failure;
            }
            if (args_info->cid_orig)
              free (args_info->cid_orig); /* free previous string */
            args_info->cid_orig = gengetopt_strdup (optarg);
          }
          /* The object ID to use.  */
          else if (strcmp (long_options[option_index].name, "oid") == 0)
          {
            if (local_args_info.oid_given)
              {
                fprintf (stderr, "%s: `--oid' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->oid_given && ! override)
              continue;
            local_args_info.oid_given = 1;
            args_info->oid_given = 1;
            args_info->oid_arg = strtol (optarg, &stop_char, 0);
            if (!(stop_char && *stop_char == '\0')) {
              fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
              goto failure;
            }
            if (args_info->oid_orig)
              free (args_info->oid_orig); /* free previous string */
            args_info->oid_orig = gengetopt_strdup (optarg);
          }
          /* The number of object to create/remove/....  */
          else if (strcmp (long_options[option_index].name, "num-objs") == 0)
          {
            if (local_args_info.num_objs_given)
              {
                fprintf (stderr, "%s: `--num-objs' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->num_objs_given && ! override)
              continue;
            local_args_info.num_objs_given = 1;
            args_info->num_objs_given = 1;
            args_info->num_objs_arg = strtol (optarg, &stop_char, 0);
            if (!(stop_char && *stop_char == '\0')) {
              fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
              goto failure;
            }
            if (args_info->num_objs_orig)
              free (args_info->num_objs_orig); /* free previous string */
            args_info->num_objs_orig = gengetopt_strdup (optarg);
          }
          /* Character string stored in an object.  */
          else if (strcmp (long_options[option_index].name, "data") == 0)
          {
            if (local_args_info.data_given)
              {
                fprintf (stderr, "%s: `--data' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->data_given && ! override)
              continue;
            local_args_info.data_given = 1;
            args_info->data_given = 1;
            if (args_info->data_arg)
              free (args_info->data_arg); /* free previous string */
            args_info->data_arg = gengetopt_strdup (optarg);
            if (args_info->data_orig)
              free (args_info->data_orig); /* free previous string */
            args_info->data_orig = gengetopt_strdup (optarg);
          }
          /* Size (bytes) of a file after the trunc test.  */
          else if (strcmp (long_options[option_index].name, "trunc-size") == 0)
          {
            if (local_args_info.trunc_size_given)
              {
                fprintf (stderr, "%s: `--trunc-size' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->trunc_size_given && ! override)
              continue;
            local_args_info.trunc_size_given = 1;
            args_info->trunc_size_given = 1;
            args_info->trunc_size_arg = strtol (optarg, &stop_char, 0);
            if (!(stop_char && *stop_char == '\0')) {
              fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
              goto failure;
            }
            if (args_info->trunc_size_orig)
              free (args_info->trunc_size_orig); /* free previous string */
            args_info->trunc_size_orig = gengetopt_strdup (optarg);
          }
          /* Name of an attribute.  */
          else if (strcmp (long_options[option_index].name, "attr-name") == 0)
          {
            if (local_args_info.attr_name_given)
              {
                fprintf (stderr, "%s: `--attr-name' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->attr_name_given && ! override)
              continue;
            local_args_info.attr_name_given = 1;
            args_info->attr_name_given = 1;
            if (args_info->attr_name_arg)
              free (args_info->attr_name_arg); /* free previous string */
            args_info->attr_name_arg = gengetopt_strdup (optarg);
            if (args_info->attr_name_orig)
              free (args_info->attr_name_orig); /* free previous string */
            args_info->attr_name_orig = gengetopt_strdup (optarg);
          }
          /* Value to store in an attribute.  */
          else if (strcmp (long_options[option_index].name, "attr-val") == 0)
          {
            if (local_args_info.attr_val_given)
              {
                fprintf (stderr, "%s: `--attr-val' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->attr_val_given && ! override)
              continue;
            local_args_info.attr_val_given = 1;
            args_info->attr_val_given = 1;
            if (args_info->attr_val_arg)
              free (args_info->attr_val_arg); /* free previous string */
            args_info->attr_val_arg = gengetopt_strdup (optarg);
            if (args_info->attr_val_orig)
              free (args_info->attr_val_orig); /* free previous string */
            args_info->attr_val_orig = gengetopt_strdup (optarg);
          }
          /* Name of the test.  */
          else if (strcmp (long_options[option_index].name, "test") == 0)
          {
            if (local_args_info.test_given)
              {
                fprintf (stderr, "%s: `--test' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if ((found = check_possible_values(optarg, cmdline_parser_test_values)) < 0)
              {
                fprintf (stderr, "%s: %s argument, \"%s\", for option `--test'%s\n", argv[0], (found == -2) ? "ambiguous" : "invalid", optarg, (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->test_given && ! override)
              continue;
            local_args_info.test_given = 1;
            args_info->test_given = 1;
            if (args_info->test_arg)
              free (args_info->test_arg); /* free previous string */
            args_info->test_arg = gengetopt_strdup (cmdline_parser_test_values[found]);
            if (args_info->test_orig)
              free (args_info->test_orig); /* free previous string */
            args_info->test_orig = gengetopt_strdup (optarg);
          }
          /* Debug level of logger [0-5].  */
          else if (strcmp (long_options[option_index].name, "verbose") == 0)
          {
            if (local_args_info.verbose_given)
              {
                fprintf (stderr, "%s: `--verbose' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->verbose_given && ! override)
              continue;
            local_args_info.verbose_given = 1;
            args_info->verbose_given = 1;
            args_info->verbose_arg = strtol (optarg, &stop_char, 0);
            if (!(stop_char && *stop_char == '\0')) {
              fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
              goto failure;
            }
            if (args_info->verbose_orig)
              free (args_info->verbose_orig); /* free previous string */
            args_info->verbose_orig = gengetopt_strdup (optarg);
          }
          /* Path to logfile.  */
          else if (strcmp (long_options[option_index].name, "logfile") == 0)
          {
            if (local_args_info.logfile_given)
              {
                fprintf (stderr, "%s: `--logfile' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->logfile_given && ! override)
              continue;
            local_args_info.logfile_given = 1;
            args_info->logfile_given = 1;
            if (args_info->logfile_arg)
              free (args_info->logfile_arg); /* free previous string */
            args_info->logfile_arg = gengetopt_strdup (optarg);
            if (args_info->logfile_orig)
              free (args_info->logfile_orig); /* free previous string */
            args_info->logfile_orig = gengetopt_strdup (optarg);
          }
          /* PID of the authr server.  */
          else if (strcmp (long_options[option_index].name, "authr-pid") == 0)
          {
            if (local_args_info.authr_pid_given)
              {
                fprintf (stderr, "%s: `--authr-pid' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->authr_pid_given && ! override)
              continue;
            local_args_info.authr_pid_given = 1;
            args_info->authr_pid_given = 1;
            args_info->authr_pid_arg = strtol (optarg, &stop_char, 0);
            if (!(stop_char && *stop_char == '\0')) {
              fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
              goto failure;
            }
            if (args_info->authr_pid_orig)
              free (args_info->authr_pid_orig); /* free previous string */
            args_info->authr_pid_orig = gengetopt_strdup (optarg);
          }
          /* NID of the authr server.  */
          else if (strcmp (long_options[option_index].name, "authr-nid") == 0)
          {
            if (local_args_info.authr_nid_given)
              {
                fprintf (stderr, "%s: `--authr-nid' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->authr_nid_given && ! override)
              continue;
            local_args_info.authr_nid_given = 1;
            args_info->authr_nid_given = 1;
            args_info->authr_nid_arg = strtol (optarg, &stop_char, 0);
            if (!(stop_char && *stop_char == '\0')) {
              fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
              goto failure;
            }
            if (args_info->authr_nid_orig)
              free (args_info->authr_nid_orig); /* free previous string */
            args_info->authr_nid_orig = gengetopt_strdup (optarg);
          }
          /* Cache caps on the client.  */
          else if (strcmp (long_options[option_index].name, "authr-cache-caps") == 0)
          {
            if (local_args_info.authr_cache_caps_given)
              {
                fprintf (stderr, "%s: `--authr-cache-caps' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->authr_cache_caps_given && ! override)
              continue;
            local_args_info.authr_cache_caps_given = 1;
            args_info->authr_cache_caps_given = 1;
            args_info->authr_cache_caps_flag = !(args_info->authr_cache_caps_flag);
          }
          /* Path to a file with a list of storage servers.  */
          else if (strcmp (long_options[option_index].name, "ss-server-file") == 0)
          {
            if (local_args_info.ss_server_file_given)
              {
                fprintf (stderr, "%s: `--ss-server-file' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->ss_server_file_given && ! override)
              continue;
            local_args_info.ss_server_file_given = 1;
            args_info->ss_server_file_given = 1;
            if (args_info->ss_server_file_arg)
              free (args_info->ss_server_file_arg); /* free previous string */
            args_info->ss_server_file_arg = gengetopt_strdup (optarg);
            if (args_info->ss_server_file_orig)
              free (args_info->ss_server_file_orig); /* free previous string */
            args_info->ss_server_file_orig = gengetopt_strdup (optarg);
          }
          /* Number of servers to use from the server file.  */
          else if (strcmp (long_options[option_index].name, "ss-num-servers") == 0)
          {
            if (local_args_info.ss_num_servers_given)
              {
                fprintf (stderr, "%s: `--ss-num-servers' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->ss_num_servers_given && ! override)
              continue;
            local_args_info.ss_num_servers_given = 1;
            args_info->ss_num_servers_given = 1;
            args_info->ss_num_servers_arg = strtol (optarg, &stop_char, 0);
            if (!(stop_char && *stop_char == '\0')) {
              fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
              goto failure;
            }
            if (args_info->ss_num_servers_orig)
              free (args_info->ss_num_servers_orig); /* free previous string */
            args_info->ss_num_servers_orig = gengetopt_strdup (optarg);
          }
          /* The PID of a single remote storage storage server (ignored if using --ss=server-file).  */
          else if (strcmp (long_options[option_index].name, "ss-pid") == 0)
          {
            if (local_args_info.ss_pid_given)
              {
                fprintf (stderr, "%s: `--ss-pid' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->ss_pid_given && ! override)
              continue;
            local_args_info.ss_pid_given = 1;
            args_info->ss_pid_given = 1;
            args_info->ss_pid_arg = strtol (optarg, &stop_char, 0);
            if (!(stop_char && *stop_char == '\0')) {
              fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
              goto failure;
            }
            if (args_info->ss_pid_orig)
              free (args_info->ss_pid_orig); /* free previous string */
            args_info->ss_pid_orig = gengetopt_strdup (optarg);
          }
          /* The NID of a single remote storage server (ignored if using --ss-server-file).  */
          else if (strcmp (long_options[option_index].name, "ss-nid") == 0)
          {
            if (local_args_info.ss_nid_given)
              {
                fprintf (stderr, "%s: `--ss-nid' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->ss_nid_given && ! override)
              continue;
            local_args_info.ss_nid_given = 1;
            args_info->ss_nid_given = 1;
            args_info->ss_nid_arg = strtol (optarg, &stop_char, 0);
            if (!(stop_char && *stop_char == '\0')) {
              fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
              goto failure;
            }
            if (args_info->ss_nid_orig)
              free (args_info->ss_nid_orig); /* free previous string */
            args_info->ss_nid_orig = gengetopt_strdup (optarg);
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



  if (check_required)
    {
      error += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}

static unsigned int
cmdline_parser_create_argv(const char *cmdline_, char ***argv_ptr, const char *prog_name)
{
  char *cmdline, *p;
  size_t n = 0, j;
  int i;

  if (prog_name) {
    cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
    cmd_line_list_tmp->next = cmd_line_list;
    cmd_line_list = cmd_line_list_tmp;
    cmd_line_list->string_arg = gengetopt_strdup (prog_name);

    ++n;
  }

  cmdline = gengetopt_strdup(cmdline_);
  p = cmdline;

  while (p && strlen(p))
    {
      j = strcspn(p, " \t");
      ++n;
      if (j && j < strlen(p))
        {
          p[j] = '\0';

          cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
          cmd_line_list_tmp->next = cmd_line_list;
          cmd_line_list = cmd_line_list_tmp;
          cmd_line_list->string_arg = gengetopt_strdup (p);

          p += (j+1);
          p += strspn(p, " \t");
        }
      else
        {
          cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
          cmd_line_list_tmp->next = cmd_line_list;
          cmd_line_list = cmd_line_list_tmp;
          cmd_line_list->string_arg = gengetopt_strdup (p);

          break;
        }
    }

  *argv_ptr = (char **) malloc((n + 1) * sizeof(char *));
  cmd_line_list_tmp = cmd_line_list;
  for (i = (n-1); i >= 0; --i)
    {
      (*argv_ptr)[i] = cmd_line_list_tmp->string_arg;
      cmd_line_list_tmp = cmd_line_list_tmp->next;
    }

  (*argv_ptr)[n] = NULL;

  free(cmdline);
  return n;
}

int
cmdline_parser_string(const char *cmdline, struct gengetopt_args_info *args_info, const char *prog_name)
{
  return cmdline_parser_string2(cmdline, args_info, prog_name, 0, 1, 1);
}

int
cmdline_parser_string2(const char *cmdline, struct gengetopt_args_info *args_info, const char *prog_name,
    int override, int initialize, int check_required)
{
  char **argv_ptr = 0;
  int result;
  unsigned int argc;
  
  argc = cmdline_parser_create_argv(cmdline, &argv_ptr, prog_name);
  
  result =
    cmdline_parser_internal (argc, argv_ptr, args_info, override, initialize, check_required, 0);
  
  if (argv_ptr)
    {
      free (argv_ptr);
    }

  free_cmd_list();
  
  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

