/* unlink_opts.h */

/* File autogenerated by gengetopt version 2.17  */

#ifndef UNLINK_OPTS_H
#define UNLINK_OPTS_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE "lwfs-tests"
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION "0.1"
#endif

struct gengetopt_args_info
{
  const char *help_help; /* Print help and exit help description.  */
  const char *version_help; /* Print version and exit help description.  */
  int total_msgs_arg;	/* The number of messages to send/receive (default='20').  */
  char * total_msgs_orig;	/* The number of messages to send/receive original value given at command line.  */
  const char *total_msgs_help; /* The number of messages to send/receive help description.  */
  int msgs_per_md_arg;	/* The number of messages per MD on the server (default='5').  */
  char * msgs_per_md_orig;	/* The number of messages per MD on the server original value given at command line.  */
  const char *msgs_per_md_help; /* The number of messages per MD on the server help description.  */
  int portal_index_arg;	/* Portals index to use (default='3').  */
  char * portal_index_orig;	/* Portals index to use original value given at command line.  */
  const char *portal_index_help; /* Portals index to use help description.  */
  int match_bits_arg;	/* Match bits to use (default='3').  */
  char * match_bits_orig;	/* Match bits to use original value given at command line.  */
  const char *match_bits_help; /* Match bits to use help description.  */
  #ifdef HAVE_LONG_LONG
  long long int server_pid_arg;	/* The process ID of the server (default=99).  */
  #else
  long server_pid_arg;	/* The process ID of the server (default=99).  */
  #endif
  char * server_pid_orig;	/* The process ID of the server original value given at command line.  */
  const char *server_pid_help; /* The process ID of the server help description.  */
  #ifdef HAVE_LONG_LONG
  long long int server_nid_arg;	/* The node ID of the server (default=-1).  */
  #else
  long server_nid_arg;	/* The node ID of the server (default=-1).  */
  #endif
  char * server_nid_orig;	/* The node ID of the server original value given at command line.  */
  const char *server_nid_help; /* The node ID of the server help description.  */
  char * msg_data_arg;	/* The data to send in each mesg (default='Hello').  */
  char * msg_data_orig;	/* The data to send in each mesg original value given at command line.  */
  const char *msg_data_help; /* The data to send in each mesg help description.  */
  int with_bug_flag;	/* Run the buggy version (default=off).  */
  const char *with_bug_help; /* Run the buggy version help description.  */
  
  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int total_msgs_given ;	/* Whether total-msgs was given.  */
  int msgs_per_md_given ;	/* Whether msgs-per-md was given.  */
  int portal_index_given ;	/* Whether portal-index was given.  */
  int match_bits_given ;	/* Whether match-bits was given.  */
  int server_pid_given ;	/* Whether server-pid was given.  */
  int server_nid_given ;	/* Whether server-nid was given.  */
  int msg_data_given ;	/* Whether msg-data was given.  */
  int with_bug_given ;	/* Whether with-bug was given.  */

} ;

extern const char *gengetopt_args_info_purpose;
extern const char *gengetopt_args_info_usage;
extern const char *gengetopt_args_info_help[];

int cmdline_parser (int argc, char * const *argv,
  struct gengetopt_args_info *args_info);
int cmdline_parser2 (int argc, char * const *argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

void cmdline_parser_init (struct gengetopt_args_info *args_info);
void cmdline_parser_free (struct gengetopt_args_info *args_info);

int cmdline_parser_string (const char *cmdline, struct gengetopt_args_info *args_info,
  const char *prog_name);
int cmdline_parser_string2 (const char *cmdline, struct gengetopt_args_info *args_info,
  const char *prog_name,
  int override, int initialize, int check_required);

int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* UNLINK_OPTS_H */
