/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "../../../../testing/xdr-tests/test_xdr.h"

bool_t
xdr_name_list_t (XDR *xdrs, name_list_t *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, NAME_LEN))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (name_list_t), (xdrproc_t) xdr_name_list_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_uuid (XDR *xdrs, lwfs_uuid objp)
{
	register int32_t *buf;

	 if (!xdr_opaque (xdrs, objp, LWFS_UUIDSIZE))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_ssid (XDR *xdrs, lwfs_ssid objp)
{
	register int32_t *buf;

	 if (!xdr_lwfs_uuid (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_vid (XDR *xdrs, lwfs_vid objp)
{
	register int32_t *buf;

	 if (!xdr_lwfs_uuid (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_uint32 (XDR *xdrs, uint32 *objp)
{
	register int32_t *buf;

	 if (!xdr_u_long (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_uint64 (XDR *xdrs, uint64 *objp)
{
	register int32_t *buf;

	 if (!xdr_u_quad_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_oid (XDR *xdrs, lwfs_oid *objp)
{
	register int32_t *buf;

	 if (!xdr_uint64 (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_did (XDR *xdrs, lwfs_did *objp)
{
	register int32_t *buf;

	 if (!xdr_uint32 (xdrs, &objp->part1))
		 return FALSE;
	 if (!xdr_uint32 (xdrs, &objp->part2))
		 return FALSE;
	 if (!xdr_uint32 (xdrs, &objp->part3))
		 return FALSE;
	 if (!xdr_uint32 (xdrs, &objp->part4))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_obj_ref (XDR *xdrs, lwfs_obj_ref *objp)
{
	register int32_t *buf;

	 if (!xdr_lwfs_ssid (xdrs, objp->ssid))
		 return FALSE;
	 if (!xdr_lwfs_vid (xdrs, objp->vid))
		 return FALSE;
	 if (!xdr_lwfs_oid (xdrs, &objp->oid))
		 return FALSE;
	 if (!xdr_lwfs_did (xdrs, &objp->dbkey))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mds_name (XDR *xdrs, mds_name *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MDS_NAME_LEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mds_dirop_args (XDR *xdrs, mds_dirop_args *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->dir, sizeof (lwfs_obj_ref), (xdrproc_t) xdr_lwfs_obj_ref))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->name, sizeof (mds_name), (xdrproc_t) xdr_mds_name))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_data_t (XDR *xdrs, data_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->int_val))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_data_array_t (XDR *xdrs, data_array_t *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->data_array_t_val, (u_int *) &objp->data_array_t_len, ~0,
		sizeof (data_t), (xdrproc_t) xdr_data_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_opaque_array (XDR *xdrs, opaque_array objp)
{
	register int32_t *buf;

	 if (!xdr_opaque (xdrs, objp, OPAQUE_ARRAY_LEN))
		 return FALSE;
	return TRUE;
}
