/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST_XDR_H_RPCGEN
#define _TEST_XDR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define NAME_LEN 256

struct name_list_t {
	char *name;
	struct name_list_t *next;
};
typedef struct name_list_t name_list_t;
#define LWFS_UUIDSIZE 16

typedef char lwfs_uuid[LWFS_UUIDSIZE];

typedef lwfs_uuid lwfs_ssid;

typedef lwfs_uuid lwfs_vid;

typedef u_long uint32;

typedef u_quad_t uint64;

typedef uint64 lwfs_oid;

struct lwfs_did {
	uint32 part1;
	uint32 part2;
	uint32 part3;
	uint32 part4;
};
typedef struct lwfs_did lwfs_did;

struct lwfs_obj_ref {
	lwfs_ssid ssid;
	lwfs_vid vid;
	lwfs_oid oid;
	struct lwfs_did dbkey;
};
typedef struct lwfs_obj_ref lwfs_obj_ref;
#define MDS_NAME_LEN 64

typedef char *mds_name;

struct mds_dirop_args {
	lwfs_obj_ref *dir;
	mds_name *name;
};
typedef struct mds_dirop_args mds_dirop_args;

struct data_t {
	int int_val;
};
typedef struct data_t data_t;

typedef struct {
	u_int data_array_t_len;
	data_t *data_array_t_val;
} data_array_t;
#define OPAQUE_ARRAY_LEN 16

typedef char opaque_array[OPAQUE_ARRAY_LEN];

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_name_list_t (XDR *, name_list_t*);
extern  bool_t xdr_lwfs_uuid (XDR *, lwfs_uuid);
extern  bool_t xdr_lwfs_ssid (XDR *, lwfs_ssid);
extern  bool_t xdr_lwfs_vid (XDR *, lwfs_vid);
extern  bool_t xdr_uint32 (XDR *, uint32*);
extern  bool_t xdr_uint64 (XDR *, uint64*);
extern  bool_t xdr_lwfs_oid (XDR *, lwfs_oid*);
extern  bool_t xdr_lwfs_did (XDR *, lwfs_did*);
extern  bool_t xdr_lwfs_obj_ref (XDR *, lwfs_obj_ref*);
extern  bool_t xdr_mds_name (XDR *, mds_name*);
extern  bool_t xdr_mds_dirop_args (XDR *, mds_dirop_args*);
extern  bool_t xdr_data_t (XDR *, data_t*);
extern  bool_t xdr_data_array_t (XDR *, data_array_t*);
extern  bool_t xdr_opaque_array (XDR *, opaque_array);

#else /* K&R C */
extern bool_t xdr_name_list_t ();
extern bool_t xdr_lwfs_uuid ();
extern bool_t xdr_lwfs_ssid ();
extern bool_t xdr_lwfs_vid ();
extern bool_t xdr_uint32 ();
extern bool_t xdr_uint64 ();
extern bool_t xdr_lwfs_oid ();
extern bool_t xdr_lwfs_did ();
extern bool_t xdr_lwfs_obj_ref ();
extern bool_t xdr_mds_name ();
extern bool_t xdr_mds_dirop_args ();
extern bool_t xdr_data_t ();
extern bool_t xdr_data_array_t ();
extern bool_t xdr_opaque_array ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEST_XDR_H_RPCGEN */
