/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "../../../../../src/common/rpc_common/service_args.h"

bool_t
xdr_lwfs_get_service_args (XDR *xdrs, lwfs_get_service_args *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_kill_service_args (XDR *xdrs, lwfs_kill_service_args *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_trace_reset_args (XDR *xdrs, lwfs_trace_reset_args *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->ftype))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->fname, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->enable_flag))
		 return FALSE;
	return TRUE;
}
