/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "../../../../../src/common/naming_common/naming_args.h"

bool_t
xdr_lwfs_create_namespace_args (XDR *xdrs, lwfs_create_namespace_args *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->txn_id, sizeof (lwfs_txn), (xdrproc_t) xdr_lwfs_txn))
		 return FALSE;
	 if (!xdr_lwfs_name (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_lwfs_cid (xdrs, &objp->cid))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_remove_namespace_args (XDR *xdrs, lwfs_remove_namespace_args *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->txn_id, sizeof (lwfs_txn), (xdrproc_t) xdr_lwfs_txn))
		 return FALSE;
	 if (!xdr_lwfs_name (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->cap, sizeof (lwfs_cap), (xdrproc_t) xdr_lwfs_cap))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_get_namespace_args (XDR *xdrs, lwfs_get_namespace_args *objp)
{
	register int32_t *buf;

	 if (!xdr_lwfs_name (xdrs, &objp->name))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_create_dir_args (XDR *xdrs, lwfs_create_dir_args *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->txn_id, sizeof (lwfs_txn), (xdrproc_t) xdr_lwfs_txn))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->parent, sizeof (lwfs_ns_entry), (xdrproc_t) xdr_lwfs_ns_entry))
		 return FALSE;
	 if (!xdr_lwfs_name (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_lwfs_cid (xdrs, &objp->cid))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->cap, sizeof (lwfs_cap), (xdrproc_t) xdr_lwfs_cap))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_remove_dir_args (XDR *xdrs, lwfs_remove_dir_args *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->txn_id, sizeof (lwfs_txn), (xdrproc_t) xdr_lwfs_txn))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->parent, sizeof (lwfs_ns_entry), (xdrproc_t) xdr_lwfs_ns_entry))
		 return FALSE;
	 if (!xdr_lwfs_name (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->cap, sizeof (lwfs_cap), (xdrproc_t) xdr_lwfs_cap))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_create_file_args (XDR *xdrs, lwfs_create_file_args *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->txn_id, sizeof (lwfs_txn), (xdrproc_t) xdr_lwfs_txn))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->parent, sizeof (lwfs_ns_entry), (xdrproc_t) xdr_lwfs_ns_entry))
		 return FALSE;
	 if (!xdr_lwfs_name (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->obj, sizeof (lwfs_obj), (xdrproc_t) xdr_lwfs_obj))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->cap, sizeof (lwfs_cap), (xdrproc_t) xdr_lwfs_cap))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_remove_file_args (XDR *xdrs, lwfs_remove_file_args *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->txn_id, sizeof (lwfs_txn), (xdrproc_t) xdr_lwfs_txn))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->parent, sizeof (lwfs_ns_entry), (xdrproc_t) xdr_lwfs_ns_entry))
		 return FALSE;
	 if (!xdr_lwfs_name (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->cap, sizeof (lwfs_cap), (xdrproc_t) xdr_lwfs_cap))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_create_link_args (XDR *xdrs, lwfs_create_link_args *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->txn_id, sizeof (lwfs_txn), (xdrproc_t) xdr_lwfs_txn))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->parent, sizeof (lwfs_ns_entry), (xdrproc_t) xdr_lwfs_ns_entry))
		 return FALSE;
	 if (!xdr_lwfs_name (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->cap, sizeof (lwfs_cap), (xdrproc_t) xdr_lwfs_cap))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->target_parent, sizeof (lwfs_ns_entry), (xdrproc_t) xdr_lwfs_ns_entry))
		 return FALSE;
	 if (!xdr_lwfs_name (xdrs, &objp->target_name))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->target_cap, sizeof (lwfs_cap), (xdrproc_t) xdr_lwfs_cap))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_unlink_args (XDR *xdrs, lwfs_unlink_args *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->txn_id, sizeof (lwfs_txn), (xdrproc_t) xdr_lwfs_txn))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->parent, sizeof (lwfs_ns_entry), (xdrproc_t) xdr_lwfs_ns_entry))
		 return FALSE;
	 if (!xdr_lwfs_name (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->cap, sizeof (lwfs_cap), (xdrproc_t) xdr_lwfs_cap))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_list_dir_args (XDR *xdrs, lwfs_list_dir_args *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->parent, sizeof (lwfs_ns_entry), (xdrproc_t) xdr_lwfs_ns_entry))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->cap, sizeof (lwfs_cap), (xdrproc_t) xdr_lwfs_cap))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_lookup_args (XDR *xdrs, lwfs_lookup_args *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->txn_id, sizeof (lwfs_txn), (xdrproc_t) xdr_lwfs_txn))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->parent, sizeof (lwfs_ns_entry), (xdrproc_t) xdr_lwfs_ns_entry))
		 return FALSE;
	 if (!xdr_lwfs_name (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_lwfs_lock_type (xdrs, &objp->lock_type))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->cap, sizeof (lwfs_cap), (xdrproc_t) xdr_lwfs_cap))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_name_stat_args (XDR *xdrs, lwfs_name_stat_args *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->txn_id, sizeof (lwfs_txn), (xdrproc_t) xdr_lwfs_txn))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->obj, sizeof (lwfs_obj), (xdrproc_t) xdr_lwfs_obj))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->cap, sizeof (lwfs_cap), (xdrproc_t) xdr_lwfs_cap))
		 return FALSE;
	return TRUE;
}
