/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NAMING_ARGS_H_RPCGEN
#define _NAMING_ARGS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#include "common/types/types.h"

struct lwfs_create_namespace_args {
	lwfs_txn *txn_id;
	lwfs_name name;
	lwfs_cid cid;
};
typedef struct lwfs_create_namespace_args lwfs_create_namespace_args;

struct lwfs_remove_namespace_args {
	lwfs_txn *txn_id;
	lwfs_name name;
	lwfs_cap *cap;
};
typedef struct lwfs_remove_namespace_args lwfs_remove_namespace_args;

struct lwfs_get_namespace_args {
	lwfs_name name;
};
typedef struct lwfs_get_namespace_args lwfs_get_namespace_args;

struct lwfs_create_dir_args {
	lwfs_txn *txn_id;
	lwfs_ns_entry *parent;
	lwfs_name name;
	lwfs_cid cid;
	lwfs_cap *cap;
};
typedef struct lwfs_create_dir_args lwfs_create_dir_args;

struct lwfs_remove_dir_args {
	lwfs_txn *txn_id;
	lwfs_ns_entry *parent;
	lwfs_name name;
	lwfs_cap *cap;
};
typedef struct lwfs_remove_dir_args lwfs_remove_dir_args;

struct lwfs_create_file_args {
	lwfs_txn *txn_id;
	lwfs_ns_entry *parent;
	lwfs_name name;
	lwfs_obj *obj;
	lwfs_cap *cap;
};
typedef struct lwfs_create_file_args lwfs_create_file_args;

struct lwfs_remove_file_args {
	lwfs_txn *txn_id;
	lwfs_ns_entry *parent;
	lwfs_name name;
	lwfs_cap *cap;
};
typedef struct lwfs_remove_file_args lwfs_remove_file_args;

struct lwfs_create_link_args {
	lwfs_txn *txn_id;
	lwfs_ns_entry *parent;
	lwfs_name name;
	lwfs_cap *cap;
	lwfs_ns_entry *target_parent;
	lwfs_name target_name;
	lwfs_cap *target_cap;
};
typedef struct lwfs_create_link_args lwfs_create_link_args;

struct lwfs_unlink_args {
	lwfs_txn *txn_id;
	lwfs_ns_entry *parent;
	lwfs_name name;
	lwfs_cap *cap;
};
typedef struct lwfs_unlink_args lwfs_unlink_args;

struct lwfs_list_dir_args {
	lwfs_ns_entry *parent;
	lwfs_cap *cap;
};
typedef struct lwfs_list_dir_args lwfs_list_dir_args;

struct lwfs_lookup_args {
	lwfs_txn *txn_id;
	lwfs_ns_entry *parent;
	lwfs_name name;
	lwfs_lock_type lock_type;
	lwfs_cap *cap;
};
typedef struct lwfs_lookup_args lwfs_lookup_args;

struct lwfs_name_stat_args {
	lwfs_txn *txn_id;
	lwfs_obj *obj;
	lwfs_cap *cap;
};
typedef struct lwfs_name_stat_args lwfs_name_stat_args;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_lwfs_create_namespace_args (XDR *, lwfs_create_namespace_args*);
extern  bool_t xdr_lwfs_remove_namespace_args (XDR *, lwfs_remove_namespace_args*);
extern  bool_t xdr_lwfs_get_namespace_args (XDR *, lwfs_get_namespace_args*);
extern  bool_t xdr_lwfs_create_dir_args (XDR *, lwfs_create_dir_args*);
extern  bool_t xdr_lwfs_remove_dir_args (XDR *, lwfs_remove_dir_args*);
extern  bool_t xdr_lwfs_create_file_args (XDR *, lwfs_create_file_args*);
extern  bool_t xdr_lwfs_remove_file_args (XDR *, lwfs_remove_file_args*);
extern  bool_t xdr_lwfs_create_link_args (XDR *, lwfs_create_link_args*);
extern  bool_t xdr_lwfs_unlink_args (XDR *, lwfs_unlink_args*);
extern  bool_t xdr_lwfs_list_dir_args (XDR *, lwfs_list_dir_args*);
extern  bool_t xdr_lwfs_lookup_args (XDR *, lwfs_lookup_args*);
extern  bool_t xdr_lwfs_name_stat_args (XDR *, lwfs_name_stat_args*);

#else /* K&R C */
extern bool_t xdr_lwfs_create_namespace_args ();
extern bool_t xdr_lwfs_remove_namespace_args ();
extern bool_t xdr_lwfs_get_namespace_args ();
extern bool_t xdr_lwfs_create_dir_args ();
extern bool_t xdr_lwfs_remove_dir_args ();
extern bool_t xdr_lwfs_create_file_args ();
extern bool_t xdr_lwfs_remove_file_args ();
extern bool_t xdr_lwfs_create_link_args ();
extern bool_t xdr_lwfs_unlink_args ();
extern bool_t xdr_lwfs_list_dir_args ();
extern bool_t xdr_lwfs_lookup_args ();
extern bool_t xdr_lwfs_name_stat_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NAMING_ARGS_H_RPCGEN */
