
#include <string.h>


/*
 * This file should be included in files that want 
 * to use command-line options for the logger.  We 
 * include the source code here because the definition
 * of gengetopt_args_info (generated by gengetopt) 
 * will change for each set of options generated by
 * the gengetopt program. 
 */

#ifndef _THREADPOOL_OPTS_H_
#define _THREADPOOL_OPTS_H_


/**
 * @brief Output the logger options to a specified file
 *
 * @param fp @input The file pointer.
 * @param opts @input The options to print.
 */
void print_threadpool_opts(
		FILE *fp, 
		const struct gengetopt_args_info *args_info, 
		const char *prefix)
{
	fprintf(fp, "%s ------------ Threadpool Options -------\n", prefix);
	fprintf(fp, "%s \ttp-init-thread-count = %d\n", prefix, 
			args_info->tp_init_thread_count_arg);
	fprintf(fp, "%s \ttp-min-thread-count = %d\n", prefix, 
			args_info->tp_min_thread_count_arg);
	fprintf(fp, "%s \ttp-max-thread-count = %d\n", prefix, 
			args_info->tp_max_thread_count_arg);
	fprintf(fp, "%s \ttp-low-watermark = %d\n", prefix, 
			args_info->tp_low_watermark_arg);
	fprintf(fp, "%s \ttp-high-watermark = %d\n", prefix, 
			args_info->tp_high_watermark_arg);
}

#endif 
