/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _XFER_H_RPCGEN
#define _XFER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data_t {
	int int_val;
	float float_val;
	double double_val;
};
typedef struct data_t data_t;

typedef struct {
	u_int data_array_t_len;
	data_t *data_array_t_val;
} data_array_t;

typedef char buf_t[16];

typedef struct {
	u_int buf_array_t_len;
	buf_t *buf_array_t_val;
} buf_array_t;

#define XFER_PROG 0x23451111
#define XFER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define data_xfer 1
extern  data_t * data_xfer_1(data_array_t *, CLIENT *);
extern  data_t * data_xfer_1_svc(data_array_t *, struct svc_req *);
#define buf_xfer 2
extern  char * buf_xfer_1(buf_array_t *, CLIENT *);
extern  char * buf_xfer_1_svc(buf_array_t *, struct svc_req *);
extern int xfer_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define data_xfer 1
extern  data_t * data_xfer_1();
extern  data_t * data_xfer_1_svc();
#define buf_xfer 2
extern  char * buf_xfer_1();
extern  char * buf_xfer_1_svc();
extern int xfer_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data_t (XDR *, data_t*);
extern  bool_t xdr_data_array_t (XDR *, data_array_t*);
extern  bool_t xdr_buf_t (XDR *, buf_t);
extern  bool_t xdr_buf_array_t (XDR *, buf_array_t*);

#else /* K&R C */
extern bool_t xdr_data_t ();
extern bool_t xdr_data_array_t ();
extern bool_t xdr_buf_t ();
extern bool_t xdr_buf_array_t ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_XFER_H_RPCGEN */
