/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "../../../../../testing/rpc-tests/rpc-xfer/xfer.h"

bool_t
xdr_data_t (XDR *xdrs, data_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->int_val))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->float_val))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->double_val))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_data_array_t (XDR *xdrs, data_array_t *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->data_array_t_val, (u_int *) &objp->data_array_t_len, ~0,
		sizeof (data_t), (xdrproc_t) xdr_data_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_buf_t (XDR *xdrs, buf_t objp)
{
	register int32_t *buf;

	 if (!xdr_opaque (xdrs, objp, 16))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_buf_array_t (XDR *xdrs, buf_array_t *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->buf_array_t_val, (u_int *) &objp->buf_array_t_len, ~0,
		sizeof (buf_t), (xdrproc_t) xdr_buf_t))
		 return FALSE;
	return TRUE;
}
