/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "xfer.h"

data_t *
data_xfer_1_svc(data_array_t *argp, struct svc_req *rqstp)
{
	static data_t  result;
	static int count = 0; 
	int len = argp->data_array_t_len;
	data_t *data = argp->data_array_t_val; 

	if ((++count) % 500 == 0) {
		fprintf(stderr, "received %d arrays (each len=%d)\n", count, len);
	}

	/* copy the last entry to the result */
	memcpy(&result, &data[len-1], sizeof(data_t));

	return &result;
}

char *
buf_xfer_1_svc(buf_array_t *argp, struct svc_req *rqstp)
{
	static buf_t result;
	static int count = 0; 
	int len = argp->buf_array_t_len;
	buf_t *buf = argp->buf_array_t_val; 

	if ((++count) % 500 == 0) {
		fprintf(stderr, "received %d arrays (each len=%d)\n", count, len);
	}

	/* copy the last entry to the result */
	memcpy(&result, &buf[len-1], sizeof(buf_t));


	return result;
}
