/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "xfer.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

data_t *
data_xfer_1(data_array_t *argp, CLIENT *clnt)
{
	static data_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, data_xfer,
		(xdrproc_t) xdr_data_array_t, (caddr_t) argp,
		(xdrproc_t) xdr_data_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

char *
buf_xfer_1(buf_array_t *argp, CLIENT *clnt)
{
	static buf_t clnt_res;

	memset((char *)clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, buf_xfer,
		(xdrproc_t) xdr_buf_array_t, (caddr_t) argp,
		(xdrproc_t) xdr_buf_t, (caddr_t) clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (clnt_res);
}
