/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "../../../../../src/common/types/xdr_types.h"
#ifdef BROKEN_DARWIN_RPCGEN

bool_t xdr_uint32_t (XDR* x, uint32_t* ii) {return xdr_u_int32_t(x,ii);}
bool_t xdr_uint64_t (XDR* x, uint64_t* ii) {return xdr_u_int64_t(x,ii);}

#endif

bool_t
xdr_lwfs_return_code (XDR *xdrs, lwfs_return_code *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_bool (XDR *xdrs, lwfs_bool *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_size (XDR *xdrs, lwfs_size *objp)
{
	register int32_t *buf;

	 if (!xdr_uint64_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_ssize (XDR *xdrs, lwfs_ssize *objp)
{
	register int32_t *buf;

	 if (!xdr_uint64_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_thread (XDR *xdrs, lwfs_thread *objp)
{
	register int32_t *buf;

	 if (!xdr_uint64_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_time (XDR *xdrs, lwfs_time *objp)
{
	register int32_t *buf;

	 if (!xdr_uint32_t (xdrs, &objp->seconds))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->nseconds))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_uuid (XDR *xdrs, lwfs_uuid objp)
{
	register int32_t *buf;

	 if (!xdr_opaque (xdrs, objp, LWFS_UUIDSIZE))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_uid (XDR *xdrs, lwfs_uid objp)
{
	register int32_t *buf;

	 if (!xdr_lwfs_uuid (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_uid_list (XDR *xdrs, lwfs_uid_list *objp)
{
	register int32_t *buf;

	 if (!xdr_lwfs_uid (xdrs, objp->uid))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (lwfs_uid_list), (xdrproc_t) xdr_lwfs_uid_list))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_uid_array (XDR *xdrs, lwfs_uid_array *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->lwfs_uid_array_val, (u_int *) &objp->lwfs_uid_array_len, ~0,
		sizeof (lwfs_uid), (xdrproc_t) xdr_lwfs_uid))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_uid_list_ptr (XDR *xdrs, lwfs_uid_list_ptr *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (lwfs_uid_list), (xdrproc_t) xdr_lwfs_uid_list))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_opstr (XDR *xdrs, lwfs_opstr objp)
{
	register int32_t *buf;

	 if (!xdr_opaque (xdrs, objp, LWFS_OP_LEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_container_op (XDR *xdrs, lwfs_container_op *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_opcode (XDR *xdrs, lwfs_opcode *objp)
{
	register int32_t *buf;

	 if (!xdr_uint32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_name (XDR *xdrs, lwfs_name *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, LWFS_NAME_LEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_name_array (XDR *xdrs, lwfs_name_array *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->lwfs_name_array_val, (u_int *) &objp->lwfs_name_array_len, ~0,
		sizeof (lwfs_name), (xdrproc_t) xdr_lwfs_name))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_acl (XDR *xdrs, lwfs_acl *objp)
{
	register int32_t *buf;

	 if (!xdr_lwfs_opcode (xdrs, &objp->opcode))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->users, sizeof (lwfs_uid_list), (xdrproc_t) xdr_lwfs_uid_list))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_opcode_list (XDR *xdrs, lwfs_opcode_list *objp)
{
	register int32_t *buf;

	 if (!xdr_lwfs_opcode (xdrs, &objp->opcode))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (lwfs_opcode_list), (xdrproc_t) xdr_lwfs_opcode_list))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_opcode_array (XDR *xdrs, lwfs_opcode_array *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->lwfs_opcode_array_val, (u_int *) &objp->lwfs_opcode_array_len, ~0,
		sizeof (lwfs_opcode), (xdrproc_t) xdr_lwfs_opcode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_opcode_list_ptr (XDR *xdrs, lwfs_opcode_list_ptr *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (lwfs_opcode_list), (xdrproc_t) xdr_lwfs_opcode_list))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_cid (XDR *xdrs, lwfs_cid *objp)
{
	register int32_t *buf;

	 if (!xdr_uint64_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_stat_data (XDR *xdrs, lwfs_stat_data *objp)
{
	register int32_t *buf;

	 if (!xdr_lwfs_time (xdrs, &objp->atime))
		 return FALSE;
	 if (!xdr_lwfs_time (xdrs, &objp->mtime))
		 return FALSE;
	 if (!xdr_lwfs_time (xdrs, &objp->ctime))
		 return FALSE;
	 if (!xdr_lwfs_size (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_oid (XDR *xdrs, lwfs_oid objp)
{
	register int32_t *buf;

	 if (!xdr_lwfs_uuid (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_vid (XDR *xdrs, lwfs_vid *objp)
{
	register int32_t *buf;

	 if (!xdr_uint32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_nid (XDR *xdrs, lwfs_nid *objp)
{
	register int32_t *buf;

	 if (!xdr_uint32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_pid (XDR *xdrs, lwfs_pid *objp)
{
	register int32_t *buf;

	 if (!xdr_uint32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_remote_pid (XDR *xdrs, lwfs_remote_pid *objp)
{
	register int32_t *buf;

	 if (!xdr_lwfs_nid (xdrs, &objp->nid))
		 return FALSE;
	 if (!xdr_lwfs_pid (xdrs, &objp->pid))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_lock_id (XDR *xdrs, lwfs_lock_id *objp)
{
	register int32_t *buf;

	 if (!xdr_uint32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_lock_type (XDR *xdrs, lwfs_lock_type *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_match_bits (XDR *xdrs, lwfs_match_bits *objp)
{
	register int32_t *buf;

	 if (!xdr_uint64_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_buffer_id (XDR *xdrs, lwfs_buffer_id *objp)
{
	register int32_t *buf;

	 if (!xdr_uint32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_rma (XDR *xdrs, lwfs_rma *objp)
{
	register int32_t *buf;

	 if (!xdr_lwfs_remote_pid (xdrs, &objp->match_id))
		 return FALSE;
	 if (!xdr_lwfs_buffer_id (xdrs, &objp->buffer_id))
		 return FALSE;
	 if (!xdr_lwfs_size (xdrs, &objp->offset))
		 return FALSE;
	 if (!xdr_lwfs_match_bits (xdrs, &objp->match_bits))
		 return FALSE;
	 if (!xdr_lwfs_size (xdrs, &objp->len))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->local_buf))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_rpc_transport (XDR *xdrs, lwfs_rpc_transport *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_rpc_encode (XDR *xdrs, lwfs_rpc_encode *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_service (XDR *xdrs, lwfs_service *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_lwfs_rpc_encode (xdrs, &objp->rpc_encode))
		 return FALSE;
	 if (!xdr_lwfs_rma (xdrs, &objp->req_addr))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->max_reqs))
		 return FALSE;
	 if (!xdr_lwfs_thread (xdrs, &objp->req_thread))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->thread_pool, MAX_SVC_THREADS,
		sizeof (lwfs_thread), (xdrproc_t) xdr_lwfs_thread))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_obj (XDR *xdrs, lwfs_obj *objp)
{
	register int32_t *buf;

	 if (!xdr_lwfs_service (xdrs, &objp->svc))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_lwfs_cid (xdrs, &objp->cid))
		 return FALSE;
	 if (!xdr_lwfs_oid (xdrs, objp->oid))
		 return FALSE;
	 if (!xdr_lwfs_lock_id (xdrs, &objp->lock_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_txn (XDR *xdrs, lwfs_txn *objp)
{
	register int32_t *buf;

	 if (!xdr_lwfs_obj (xdrs, &objp->journal))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_distributed_obj (XDR *xdrs, lwfs_distributed_obj *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->chunk_size))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ss_obj_count))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->ss_obj, sizeof (lwfs_obj), (xdrproc_t) xdr_lwfs_obj))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_ns_entry (XDR *xdrs, lwfs_ns_entry *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->name, LWFS_NAME_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_lwfs_oid (xdrs, objp->dirent_oid))
		 return FALSE;
	 if (!xdr_lwfs_oid (xdrs, objp->inode_oid))
		 return FALSE;
	 if (!xdr_lwfs_oid (xdrs, objp->parent_oid))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->link_cnt))
		 return FALSE;
	 if (!xdr_lwfs_obj (xdrs, &objp->entry_obj))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->file_obj, sizeof (lwfs_obj), (xdrproc_t) xdr_lwfs_obj))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->d_obj, sizeof (lwfs_distributed_obj), (xdrproc_t) xdr_lwfs_distributed_obj))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_ns_entry_array (XDR *xdrs, lwfs_ns_entry_array *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->lwfs_ns_entry_array_val, (u_int *) &objp->lwfs_ns_entry_array_len, ~0,
		sizeof (lwfs_ns_entry), (xdrproc_t) xdr_lwfs_ns_entry))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_namespace (XDR *xdrs, lwfs_namespace *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->name, LWFS_NAME_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_lwfs_ns_entry (xdrs, &objp->ns_entry))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_namespace_array (XDR *xdrs, lwfs_namespace_array *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->lwfs_namespace_array_val, (u_int *) &objp->lwfs_namespace_array_len, ~0,
		sizeof (lwfs_namespace), (xdrproc_t) xdr_lwfs_namespace))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_entry_type (XDR *xdrs, lwfs_entry_type *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_pt_indices (XDR *xdrs, lwfs_pt_indices *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_request_header (XDR *xdrs, lwfs_request_header *objp)
{
	register int32_t *buf;

	 if (!xdr_u_long (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_lwfs_opcode (xdrs, &objp->opcode))
		 return FALSE;
	 if (!xdr_lwfs_bool (xdrs, &objp->fetch_args))
		 return FALSE;
	 if (!xdr_lwfs_rma (xdrs, &objp->args_addr))
		 return FALSE;
	 if (!xdr_lwfs_rma (xdrs, &objp->data_addr))
		 return FALSE;
	 if (!xdr_lwfs_rma (xdrs, &objp->res_addr))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_result_header (XDR *xdrs, lwfs_result_header *objp)
{
	register int32_t *buf;

	 if (!xdr_u_long (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_lwfs_bool (xdrs, &objp->fetch_result))
		 return FALSE;
	 if (!xdr_lwfs_rma (xdrs, &objp->result_addr))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->rc))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_key (XDR *xdrs, lwfs_key objp)
{
	register int32_t *buf;

	 if (!xdr_opaque (xdrs, objp, LWFS_KEYSIZE))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_mac (XDR *xdrs, lwfs_mac objp)
{
	register int32_t *buf;

	 if (!xdr_opaque (xdrs, objp, LWFS_MACSIZE))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_cred_data (XDR *xdrs, lwfs_cred_data *objp)
{
	register int32_t *buf;

	 if (!xdr_lwfs_uid (xdrs, objp->uid))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_cred (XDR *xdrs, lwfs_cred *objp)
{
	register int32_t *buf;

	 if (!xdr_lwfs_cred_data (xdrs, &objp->data))
		 return FALSE;
	 if (!xdr_lwfs_mac (xdrs, objp->mac))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_cap_data (XDR *xdrs, lwfs_cap_data *objp)
{
	register int32_t *buf;

	 if (!xdr_lwfs_cid (xdrs, &objp->cid))
		 return FALSE;
	 if (!xdr_lwfs_container_op (xdrs, &objp->container_op))
		 return FALSE;
	 if (!xdr_lwfs_cred (xdrs, &objp->cred))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_cap (XDR *xdrs, lwfs_cap *objp)
{
	register int32_t *buf;

	 if (!xdr_lwfs_cap_data (xdrs, &objp->data))
		 return FALSE;
	 if (!xdr_lwfs_mac (xdrs, objp->mac))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_cap_array (XDR *xdrs, lwfs_cap_array *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->lwfs_cap_array_val, (u_int *) &objp->lwfs_cap_array_len, ~0,
		sizeof (lwfs_cap), (xdrproc_t) xdr_lwfs_cap))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_cap_list (XDR *xdrs, lwfs_cap_list *objp)
{
	register int32_t *buf;

	 if (!xdr_lwfs_cap (xdrs, &objp->cap))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (lwfs_cap_list), (xdrproc_t) xdr_lwfs_cap_list))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_cap_list_ptr (XDR *xdrs, lwfs_cap_list_ptr *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (lwfs_cap_list), (xdrproc_t) xdr_lwfs_cap_list))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_attr_data (XDR *xdrs, lwfs_attr_data *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->lwfs_attr_data_val, (u_int *) &objp->lwfs_attr_data_len, LWFS_ATTR_SIZE))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_attr (XDR *xdrs, lwfs_attr *objp)
{
	register int32_t *buf;

	 if (!xdr_lwfs_name (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_lwfs_attr_data (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lwfs_attr_array (XDR *xdrs, lwfs_attr_array *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->lwfs_attr_array_val, (u_int *) &objp->lwfs_attr_array_len, ~0,
		sizeof (lwfs_attr), (xdrproc_t) xdr_lwfs_attr))
		 return FALSE;
	return TRUE;
}
