/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AUTHR_ARGS_H_RPCGEN
#define _AUTHR_ARGS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#include "common/types/types.h"

struct lwfs_create_container_args {
	lwfs_txn *txn_id;
	lwfs_cid cid;
	lwfs_cap *cap;
};
typedef struct lwfs_create_container_args lwfs_create_container_args;

struct lwfs_remove_container_args {
	lwfs_txn *txn_id;
	lwfs_cid cid;
	lwfs_cap *cap;
};
typedef struct lwfs_remove_container_args lwfs_remove_container_args;

struct lwfs_create_acl_args {
	lwfs_txn *txn_id;
	lwfs_cid cid;
	lwfs_container_op container_op;
	lwfs_uid_array *set;
	lwfs_cap *cap;
};
typedef struct lwfs_create_acl_args lwfs_create_acl_args;

struct lwfs_get_acl_args {
	lwfs_cid cid;
	lwfs_container_op container_op;
	lwfs_cap *cap;
};
typedef struct lwfs_get_acl_args lwfs_get_acl_args;

struct lwfs_mod_acl_args {
	lwfs_txn *txn_id;
	lwfs_cid cid;
	lwfs_container_op container_op;
	lwfs_uid_array *set;
	lwfs_uid_array *unset;
	lwfs_cap *cap;
};
typedef struct lwfs_mod_acl_args lwfs_mod_acl_args;

struct lwfs_get_cap_args {
	lwfs_cid cid;
	lwfs_container_op container_op;
	lwfs_cred *cred;
};
typedef struct lwfs_get_cap_args lwfs_get_cap_args;

struct lwfs_verify_caps_args {
	lwfs_cap_array *cap_array;
};
typedef struct lwfs_verify_caps_args lwfs_verify_caps_args;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_lwfs_create_container_args (XDR *, lwfs_create_container_args*);
extern  bool_t xdr_lwfs_remove_container_args (XDR *, lwfs_remove_container_args*);
extern  bool_t xdr_lwfs_create_acl_args (XDR *, lwfs_create_acl_args*);
extern  bool_t xdr_lwfs_get_acl_args (XDR *, lwfs_get_acl_args*);
extern  bool_t xdr_lwfs_mod_acl_args (XDR *, lwfs_mod_acl_args*);
extern  bool_t xdr_lwfs_get_cap_args (XDR *, lwfs_get_cap_args*);
extern  bool_t xdr_lwfs_verify_caps_args (XDR *, lwfs_verify_caps_args*);

#else /* K&R C */
extern bool_t xdr_lwfs_create_container_args ();
extern bool_t xdr_lwfs_remove_container_args ();
extern bool_t xdr_lwfs_create_acl_args ();
extern bool_t xdr_lwfs_get_acl_args ();
extern bool_t xdr_lwfs_mod_acl_args ();
extern bool_t xdr_lwfs_get_cap_args ();
extern bool_t xdr_lwfs_verify_caps_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AUTHR_ARGS_H_RPCGEN */
